### ISSUE TITLE
try example

### ISSUE THREAD

**Issue by almemar87** [ademc/bg-player#1]
sorry dear, I'm new in this field. 
how to implement the example? in which file index.html or .js? and does it work with youtube embed in html? 
many thanks

**Comment by ademc** [comment]
This is a [cordova](https://cordova.apache.org/) plugin. After create a cordova project you can install with this command:

`cordova plugin add https://github.com/ademc/bg-player.git`

After that you can use features (js methods) mentioned from readme.md
